sbpp_main (Update)
sbpp/sourcebans-pp pull request #475
Opened 2018-05-23 18:05 UTC by cRUSHER-HLG

- Adding Forward OnPlayerBlocked
- Changing Syntax to sm 1.7
- Updating the Updater Lib also to the new sm 1.7 syntax.
- The automated build will fail because they dont use my updated updater.inc
-! I forgot to change the description in sourcebanspp.inc for the new added forward.

## Motivation and Context

The changes are not required but a good base for the future. The sm 1.7 syntax is more and more in use.

## How Has This Been Tested?

Its tested on my TestServer for the game csgo.

## Screenshots (if appropriate):

## Types of changes

- [#] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

2018-05-23 22:28 UTC, rumblefrog requested changes

2018-05-23 22:28 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +			TopMenuObject res = AddToTopMenu(hTopMenu, "sm_ban",  TopMenuObject_Item, AdminMenu_Ban, player_commands, "sm_ban", ADMFLAG_BAN);
Use the method map here

2018-05-23 22:28 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +			AddToTopMenu(hTopMenu, "sm_ban", TopMenuObject_Item, AdminMenu_Ban, player_commands, "sm_ban", ADMFLAG_BAN);
Use the method map here

2018-05-23 22:28 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void AdminMenu_Ban(Handle topmenu, TopMenuAction action, TopMenuObject object_id, int param, char[] buffer, int maxlength)
Replace generic handle declaration for `topmenu`

2018-05-23 22:28 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void VerifyInsert(Handle owner, Handle hndl, const char[] error, DataPack dataPack)
While here, use the new SQLQueryCallback typedef

2018-05-23 22:28 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void SelectBanIpCallback(Handle owner, Handle hndl, const char[] error, any data)
Same here, new typedef. And `data` type declaration can be `DataPack`

2018-05-23 22:28 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	ResetPack(data);	// Reset Position in DataPack.
Here to below, use the DataPack method map

2018-05-23 22:28 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void InsertBanIpCallback(Handle owner, Handle hndl, const char[] error, any data)
New typedef

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char arg[30];
You can merge these two char lines

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void SelectUnbanCallback(Handle owner, Handle hndl, const char[] error, any data)
New typedef & `data` type declaration

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void InsertUnbanCallback(Handle owner, Handle hndl, const char[] error, any data)
Typedef & `data` type declaration can be `DataPack`

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void SelectAddbanCallback(Handle owner, Handle hndl, const char[] error, any data)
Typedef & `data` type declaration

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void InsertAddbanCallback(Handle owner, Handle hndl, const char[] error, any data)
Typedef & type

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void ProcessQueueCallback(Handle owner, Handle hndl, const char[] error, any data)
Typedef & type

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char reason[128];
You can merge all these lines

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
>  	while (SQL_MoreRows(hndl))
Although you did not modify this section, using the new typedef, you may use the method map for more rows.

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +			Handle authPack = CreateDataPack();
`new DataPack();`

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char auth[40];
Merge

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void AddedFromSQLiteCallback(Handle owner, Handle hndl, const char[] error, any data)
Typedef & data type

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void ServerInfoCallback(Handle owner, Handle hndl, const char[] error, any data)
Typedef & data type

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void ErrorCheckCallback(Handle owner, Handle hndl, const char[] error, any data)
Typedef & data type

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +#pragma dynamic 131072
Is there a need to allocate additional stack size?

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +char ServerPort[7];
This section was already fine, but you don't have to change it back.

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char authType[] = "steam";
Merge

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void AdminsDone(Handle owner, Handle hndl, const char[] error, any data)
Typedef, you can leave data to any as none is passed

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +		int curPos = 0;
Merge

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void GroupsDone(Handle owner, Handle hndl, const char[] error, any data)
Typedef, leave data type to any as none is passed

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	int Immunity;
Merge

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void GroupsSecondPass(Handle owner, Handle hndl, const char[] error, any data)
I believe this block can be deleted, as the only call is commented out

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	GroupId immuneGrp = INVALID_GROUP_ID;
Merge

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	OverrideType iType;
Merge

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void LoadGroupsOverrides(Handle owner, Handle hndl, const char[] error, any data)
Typedef, leave data

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	Handle groupsKV = CreateKeyValues("Groups");
Generic type declaration, use `KeyValues`

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	Handle hKV = CreateKeyValues("SB_Overrides");
Generic type declaration

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void OverridesDone(Handle owner, Handle hndl, const char[] error, any data)
Typedef, leave data

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public Action ClientRecheck(Handle timer, any client)
`client` type declaration

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public SMCResult ReadConfig_NewSection(Handle smc, const char[] name, bool opt_quotes)
`smc` type declaration

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public SMCResult ReadConfig_KeyValue(Handle smc, const char[] key, const char[] value, bool key_quotes, bool value_quotes)
`smc` type declaration

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public SMCResult ReadConfig_EndSection(Handle smc)
`smc` type declaration

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	int iTarget = GetNativeCell(2);
Again not necessary, but you already have done it.

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	dataPack.WriteCell(view_as<char>(reasonPack));
should be int?

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char banName[128];
Merge

2018-05-23 22:28 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	CreateConVar("sb_version", SB_VERSION, _, FCVAR_NOTIFY);
SPONLY and REPLICATED flags should remain

2018-05-23 22:29 UTC, RumbleFrog commented
I have reviewed this PR mostly, note some of the changes are optional but a bonus. But some are required for a response.

2018-05-23 22:48 UTC, cRUSHER-HLG commented
I change it later then

2018-05-23 23:19 UTC, rumblefrog requested changes

2018-05-23 23:19 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/include/updater.inc
> +#if defined _updater_included
I also believe we shouldn't include updater dependency as it's not part of SB, if people want to compile it with updater they should pull it from the respective source

2018-05-24 06:06 UTC, cRUSHER-HLG commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	OverrideType iType;
Cant merge here because iRule and iType has different types.

2018-05-24 06:09 UTC, cRUSHER-HLG commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public SMCResult ReadConfig_NewSection(Handle smc, const char[] name, bool opt_quotes)
Which type must smc have?

2018-05-24 11:38 UTC, rumblefrog requested changes

2018-05-24 11:38 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/include/sourcebanspp.inc
> + * (game = csgo: you where banned not includes, only if loading screen appiers it counts.)
This documentation doesn't seem to be grammatically correct

2018-06-17 18:57 UTC, RumbleFrog commented
Now being handled by #483

2018-06-17 18:57 UTC, closed without merging