Full SM transitional syntax upconversion including methodmaps
sbpp/sourcebans-pp pull request #483
Opened 2018-06-17 13:24 UTC by geominorai

Converted all pre-transitional code to comply with new SM syntax
Code has also been refactored to use method maps and their updated callbacks where applicable
A few DataPack memory leaks were also patched and minor code styles tidied up

## Description
Method map usage include:
- AdminId
- ArrayList
- ConVar
- Database
- DataPack
- DBResultSet
- File
- KeyValues
- Menu
- Panel
- SMCParser
- TopMenu

## Motivation and Context
Improve readability with syntax standardization for ease of future debugging and development.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Compiler requirements have been upped to SM 1.7+.  All compatibility legacy code for pre-transitional syntax compilers have been removed.

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

2018-06-17 18:44 UTC, rumblefrog requested changes
Good job 👍  Just need few edits

2018-06-17 18:44 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_comms.sp
>  				#else
You can remove the sourcemod version check and use the latest, moving forward we are only going to permit 1.8+

2018-06-17 18:44 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +		cgar auth[64];
I too love cgar

2018-06-17 18:44 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +		ThrowNativeError(SP_ERROR_NATIVE, "Permanent gag is not allowed!");
All ThrowNativeError should return to stop the execution of the rest

2018-06-17 18:44 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void OnAdminMenuReady(Handle hTemp)
This type could be `TopMenu`

2018-06-17 18:44 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	TopMenu topmenu = view_as<TopMenu>(hTemp);
Then this casting wouldn't be needed

2018-06-17 18:49 UTC, geominorai commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +		ThrowNativeError(SP_ERROR_NATIVE, "Permanent gag is not allowed!");
Good catch, looks like I forgot that fix one.

2018-06-17 18:50 UTC, geominorai commented on game/addons/sourcemod/scripting/sbpp_comms.sp
>  				#else
Roger that.

2018-06-17 18:54 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void OnAdminMenuReady(Handle hTemp)
Never mind on this, apparently Sourcemod still uses `Handle` as the type for this. This could be a separate PR to Sourcemod to change this.

2018-06-17 18:54 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	TopMenu topmenu = view_as<TopMenu>(hTemp);
Above.

2018-06-17 18:57 UTC, geominorai commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void OnAdminMenuReady(Handle hTemp)
I actually can't compile this with TopMenu.  Looks like the compiler's forcing the Handle in the prototype:
` function argument named 'topmenu' differs from prototype`

2018-06-17 19:00 UTC, RumbleFrog commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void OnAdminMenuReady(Handle hTemp)
Yeah, that's a PR to Sourcemod, for another day

2018-06-17 19:06 UTC, rumblefrog approved these changes

2018-06-18 06:04 UTC, CrazyHackGUT commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +		ThrowNativeError(SP_ERROR_NATIVE, "Permanent gag is not allowed!");
This is not required. Just compare implementations [ThrowNative()](https://github.com/alliedmodders/sourcemod/blob/master/core/logic/smn_core.cpp#L161) and [ThrowNativeError()](https://github.com/alliedmodders/sourcemod/blob/master/core/logic/smn_fakenatives.cpp#L147).

2018-06-18 06:05 UTC, CrazyHackGUT commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +public void OnAdminMenuReady(Handle hTemp)
This is not `TopMenu` handle. This is generic handle. Check API.
https://sm.alliedmods.net/new-api/topmenus/TopMenu/FromHandle

2018-06-18 14:44 UTC, Groruk approved these changes

2018-06-18 14:45 UTC, merged

2018-06-18 19:05 UTC, geominorai commented
Thanks for taking the time to review this long commit guys. 👍