Translations for sbpp checker
sbpp/sourcebans-pp pull request #525
Opened 2018-10-18 01:52 UTC by sneak-it

## Description

I have updated sbpp_checker to utilize translations, defined a prefix as with sbpp_main & sbpp_comms, and tweaked a small bit of the language (english) to be a bit more grammatically correct. I have also updated sbpp_sleuth to utilize a prefix, to be uniform with all other plugins, just like above.

## Motivation and Context

Don't think this fixes any issues or requests, but provides increased multilingual support.

## How Has This Been Tested?

I have tested these changes in depth on both a private and populated public server, however additional testing certainly would not hurt!

## Screenshots (if appropriate):
![https://share.snksrv.com/i/teu58R.png](Screenshot)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

This will require an additional translation file for the checker. Upon next release servers will require this file, so not really breaking.

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

2018-10-18 04:33 UTC, CrazyHackGUT commented
You don't fully utilize translations.
In `PrintToBanAdmins()` you should move `VFormat()` in `for` block, and before calling `VFormat()`, call `SetGlobalTransTarget()`.
This causes a bug when checker is utilize translations, but prints for all clients message on one language.

2018-10-18 04:33 UTC, CrazyHackGUT requested changes
https://github.com/sbpp/sourcebans-pp/pull/525#issuecomment-430872055

2018-10-18 06:17 UTC, sneak-it commented
Good catch! This should be fixed, thank you.

2018-10-18 08:42 UTC, CrazyHackGUT commented on game/addons/sourcemod/scripting/sbpp_checker.sp
> +		VFormat(msg, sizeof(msg), format, 2);
This two functions should be called after checking, in game client or not.

2018-10-18 17:33 UTC, sneak-it commented
Fixed, along with a mistake I made in sleuth that went unnoticed.

2018-10-18 18:33 UTC, sneak-it commented
Just saw this commit: https://github.com/sbpp/sourcebans-pp/commit/42e3206b910f3d4af6a68299f6e4abda488d01e7

@Groruk should this translation file be renamed to sbpp_checker.phrases.txt ?

2018-10-18 18:46 UTC, Groruk commented
> 
> 
> Just saw this commit: [42e3206](https://github.com/sbpp/sourcebans-pp/commit/42e3206b910f3d4af6a68299f6e4abda488d01e7)
> 
> @Groruk should this translation file be renamed to sbpp_checker.phrases.txt ?

yes, that would be nice. (just to be inline with plugin names)

2018-10-18 20:21 UTC, sneak-it commented
Done!

2018-10-19 02:23 UTC, CrazyHackGUT approved these changes

2018-10-20 03:27 UTC, rumblefrog approved these changes

2018-10-20 21:35 UTC, merged