Add a native to ban a steam ID with a parameter to bind the steam ID with a name and a parameter to kick if online.
sbpp/sourcebans-pp pull request #688
Opened 2020-08-18 15:10 UTC by eyal282

This is the native's structure, without it it's impossible to ban a steam ID with a name attached to it.

`/*********************************************************
 * Ban Identity from server
 *
 * @param authid		The authid to ban
 * @param admin			The admin's client index
 * @param time			The time to ban the player for (in minutes, 0 = permanent)
 * @param reason		The reason to ban the player from the server
 * @param kick			True if to kick the banned player if he is inside the server.
 * @param name			The name of the banned client that owns the identity.
 * @noreturn
 *********************************************************/
native void SBBanAuthId(const char[] AuthId, int iAdmin, int iTime, const char[] sReason, bool kick=true, const char[] Name="");`

2020-08-19 07:16 UTC, TheByKotik commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +		strcopy(reason, sizeof(reason), "Banned by SourceBans");
Since this is `native` player will not be banned through SB I suppose.

2020-08-19 07:18 UTC, TheByKotik commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char name[64];
I think we must use `MAX_NAME_LENGTH` (128) const. Too short for now.

2020-08-19 09:39 UTC, eyal282 commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +		strcopy(reason, sizeof(reason), "Banned by SourceBans");
Any specific suggestions? "Banned by Sourcemod plugin"

2020-08-19 09:52 UTC, eyal282 commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char name[64];
It's actually MAX_NAME_LENGTH + 1 because of the character "End Of String" ( EOS ) and it appears throughout the whole plugin.

2020-08-19 10:16 UTC, eyal282 commented
@TheByKotik 

I asked in the Alliedmods Discord and according to asherkin, the issue in the checks is SBPP and not mine.

2020-08-19 16:26 UTC, Groruk requested changes

2020-08-19 16:26 UTC, Groruk commented on game/addons/sourcemod/scripting/include/sourcebanspp.inc
> +native void SBBanAuthId(const char[] AuthId, int iAdmin, int iTime, const char[] sReason, bool kick=true, const char[] Name="");
New SourceBans++ natives have the prefix `SBPP_` as to not confuse them with natives from the original SourceBans, so you should change the name to `SBPP_BanAuthId`

2020-08-19 16:26 UTC, Groruk commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +		ReplyToCommand(admin, "You do not have Perm Ban Permission");
Instead of hardcoding an english string, a [Sourcemod translation](https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)) would be more fitting.

2020-08-19 16:26 UTC, Groruk commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +			continue;
Could be simplified to 
```sourcepawn
if (!IsClientInGame(i) || !IsClientAuthorized(i))
    continue;
```

2020-08-19 16:26 UTC, Groruk commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +			return i;
Would this check work if a plugins calls the native with a Steam2 ID (e.g `STEAM_0:1:47783783`), but the server engine uses Steam3 IDs (e.g `[U:1:95567567]`)?

2020-08-19 16:41 UTC, TheByKotik commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +			return i;
Actually this param must be replaced by Steam Account ID.

2020-08-19 18:51 UTC, eyal282 commented
@Groruk 

I tried evening everything my fork was behind, possibly doing harm. Tell me if you see anything obvious please.

2020-08-19 20:11 UTC, Groruk reviewed
I fixed some of the smaller mistakes and dropped the commits that caused merge confilicts.

2020-08-19 20:11 UTC, Groruk commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +			return i;
This is still a problem and a simple AuthIdType change will not fix this.
Best solution would be to use AccountIDs like @TheByKotik suggested.

2020-08-20 03:48 UTC, TheByKotik commented on game/addons/sourcemod/scripting/include/sourcebanspp.inc
> +native void SBPP_BanAccountId(const char[] AuthId, int iAdmin, int iTime, const char[] sReason, bool kick=true, const char[] Name="");
AccountID have `int` type. Param must be like `const int iAccountID`.

2020-08-20 03:55 UTC, TheByKotik commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	FormatEx(buffer, bufferLen, "STEAM_1:%d:%d", AccountId % 2, RoundFloor(float(AccountId) / 2.0))
1. Use `%u` instead `%d` or `%i` for correct formatting account id's in future (after MAX SINGNED INT).
2. Database uses old universe steamid's as i remebmer. `STEAM_0:%u:%u`
Please, replace it by:
```
FormatEx( buffer, bufferLen, "STEAM_0:%u:%u", iAccountID & 1, iAccountID >> 1 );
```

2020-08-20 03:57 UTC, TheByKotik commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	char authid[64];
You also can reduce this to `22+1 /* sizeof "STEAM_255:1:2147483647". */`.

2020-08-20 04:05 UTC, TheByKotik commented
You also changed every end-of-line in sourcebanspp.inc from `LF` to `CRLF`.
I think it would be a good idea to revert this.

2020-08-20 08:00 UTC, eyal282 commented on game/addons/sourcemod/scripting/include/sourcebanspp.inc
> +native void SBPP_BanAccountId(const char[] AuthId, int iAdmin, int iTime, const char[] sReason, bool kick=true, const char[] Name="");
Wait, don't integers not use const and reference uses & or it's because of the uint32? I'll do what you said regardless.

2020-08-20 08:07 UTC, TheByKotik commented on game/addons/sourcemod/scripting/include/sourcebanspp.inc
> +native void SBPP_BanAccountId(const char[] AuthId, int iAdmin, int iTime, const char[] sReason, bool kick=true, const char[] Name="");
> Wait, don't integers not use const and reference uses & or it's because of the uint32? I'll do what you said regardless.

`const' modifier simply marks a variable for a compiler as "we don't want to change it, please warn us if we try".

2020-08-20 08:41 UTC, eyal282 commented
> You also changed every end-of-line in sourcebanspp.inc from `LF` to `CRLF`.
> I think it would be a good idea to revert this.

I have no idea what this means, I can't think of anything to fix this. All else is fixed.

2020-08-20 13:53 UTC, eyal282 commented
@Groruk 

I made a simple test on my server and the plugin is working.

2020-08-23 17:28 UTC, eyal282 commented
@TheByKotik 

Any issues left? I confirmed everything on plain sight indeed works.

2020-08-24 09:18 UTC, eyal282 commented
I think IP Address is another thing that could and should be binded. Once the PR is accepted it may be too late. Thoughts?

2020-08-29 05:16 UTC, geominorai commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +		strcopy(reason, sizeof(reason), "Banned by SourceBans");
FYI, you can check for empty strings with just `if (!reason[0])`.

2020-08-29 06:57 UTC, TheByKotik commented on game/addons/sourcemod/scripting/include/sourcebanspp.inc
> +//  Copyright (C) 2014-2016 SourceBans++ Dev Team <https://github.com/sbpp>
You change year.

2020-08-29 07:00 UTC, TheByKotik commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	if (!time && client && !(CheckCommandAccess(client, "sm_unban", ADMFLAG_UNBAN)))
You change flag but PR header tell only about adding native?

2020-08-29 13:02 UTC, eyal282 commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +	if (!time && client && !(CheckCommandAccess(client, "sm_unban", ADMFLAG_UNBAN)))
Fixed some issues. I was told by Asherkin that it will just evaluate to ADMFLAG_ROOT, which is a bug. Just fixed some small stuff just for the sake of doing it. Also, CheckCommandAccess always returns true for root.

2020-08-29 13:03 UTC, eyal282 commented on game/addons/sourcemod/scripting/include/sourcebanspp.inc
> +//  Copyright (C) 2014-2016 SourceBans++ Dev Team <https://github.com/sbpp>
Probably used an include from my folder. Is there anything else I edited by accident?

2020-08-29 13:07 UTC, eyal282 commented on game/addons/sourcemod/scripting/sbpp_main.sp
> +		strcopy(reason, sizeof(reason), "Banned by SourceBans");
I use EOS always. I copied from another part so the syntax you guys use is the same.

2020-09-20 21:51 UTC, BrutalCSEjziponken commented
Looking forward to this. :)

2020-11-12 18:54 UTC, eyal282 commented
I feel like this is going nowhere due to communication difficulties, likely on me. I hope someone can just, literally, take everything I did and add this native so we can use Ban Disconnected properly, I already have the plugin published.

2020-11-12 18:54 UTC, closed without merging