Fix #869 & #870
sbpp/sourcebans-pp pull request #871
Opened 2023-03-11 13:16 UTC by Rushaway

## Description

- Fix the value of the datapack was 16 instead of 6.
- `g_bPlayerStatus` value is now based on `IsClientAuthorized` return value 

## Motivation and Context

Fix #869 & #870

## How Has This Been Tested?

- When retrying to reproduct #869 no more error and unblock work well.
- Wasn't able to have again false flag for #870

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

2023-03-15 03:36 UTC, rumblefrog requested changes

2023-03-15 03:36 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +				dataPack.Position = view_as<DataPackPos>(6);
I believe we should resolve the issue of using view_as<DataPackPos>; DataPackPos is never meant to be used this way

They are references to SP internals, which could be wrong someday; we should stop reading cells to get to the proper position.

2023-04-06 22:32 UTC, Hackmastr commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +				dataPack.Position = view_as<DataPackPos>(6);
@Rushaway any update on this?

2023-04-07 06:06 UTC, Rushaway commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +				dataPack.Position = view_as<DataPackPos>(6);
I will try to get a deeper look on it this week. I'm bus as hell these week.

2023-05-07 11:09 UTC, rumblefrog commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +				dataPack.ReadCell();
Sanity check here, is a single readcell actually skipping to 16?

2023-05-19 16:45 UTC, DosMike commented on game/addons/sourcemod/scripting/sbpp_comms.sp
> +	if (strncmp(clientAuth[6], "ID_", 3) != -1 || clientAuth[0] == 'B')
Shouldn't the [`strncmp`](https://sourcemod.dev/#/string/function.strncmp)s (across the PR) compare to `== 0` to test for equality? This is not [`StrContains`](https://sourcemod.dev/#/string/function.StrContains), which returns -1 if the search string is not contained.

2023-05-25 19:30 UTC, Rushaway commented
@cruze03 You was reading cell to the second position instead of 3.

2023-08-06 08:25 UTC, closed without merging